### ISSUE TITLE
Horse Spawn Locations

### ISSUE THREAD

**Issue by SullyR9** [RexShack/rsg_stable#1]
Whenever I press H to call my horse, it spawns it in The Heartlands, rather than near my player

**Comment by RexShack** [comment]
for best results when not using your horse always flee it / but will check the code as I have never had this issue

**Comment by wrathster2103** [comment]
Ive had this happen to me today

**Comment by SullyR9** [comment]
> for best results when not using your horse always flee it / but will check the code as I have never had this issue

I have tried fleeing it but having the same issue, its happening for new players as well, where they buy / select their horse, try call it and it never comes

**Comment by RexShack** [comment]
when you buy a horse you there is an issue where you need to relog for it to register

**Comment by SullyR9** [comment]
No it registers fine I think, someone im testing with has tried relogging but it still doesnt spawn in

**Comment by RexShack** [comment]
made a change to the code which should handle the calculation better from player to horse / if the horse is greater the 100 distance it will delete it and use your whistle again and should spawn again
